<a href="https://colab.research.google.com/github/marwankashef/NLP/blob/master/NLP_Deep_Learning_Chatbot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pickle
import numpy as np


In [ ]:
with open('/content/drive/My Drive/UPDATED_NLP_COURSE/06-Deep-Learning/train_qa.txt','rb') as f:
  train_data = pickle.load(f)

In [ ]:
with open('/content/drive/My Drive/UPDATED_NLP_COURSE/06-Deep-Learning/test_qa.txt','rb') as f:
  test_data = pickle.load(f)

In [ ]:
type(test_data)

list

In [ ]:
len(train_data)

10000

In [ ]:
len(test_data)

1000

In [ ]:
train_data[0]

(['Mary',
  'moved',
  'to',
  'the',
  'bathroom',
  '.',
  'Sandra',
  'journeyed',
  'to',
  'the',
  'bedroom',
  '.'],
 ['Is', 'Sandra', 'in', 'the', 'hallway', '?'],
 'no')

In [ ]:
' '.join(train_data[0][0])

'Mary moved to the bathroom . Sandra journeyed to the bedroom .'

In [ ]:
' '.join(train_data[0][1])

'Is Sandra in the hallway ?'

In [ ]:
train_data[0][2]

'no'

In [ ]:
all_data = test_data + train_data

In [ ]:
len(all_data)

11000

In [ ]:
set(train_data[0][0])

{'.',
 'Mary',
 'Sandra',
 'bathroom',
 'bedroom',
 'journeyed',
 'moved',
 'the',
 'to'}

In [ ]:
vocab = set()

for story, question, answer in all_data:
  vocab = vocab.union(set(story))
  vocab = vocab.union(set(question))

In [ ]:
vocab.add('no')

In [ ]:
vocab.add('yes')

In [ ]:
sorted(vocab)

['.',
 '?',
 'Daniel',
 'Is',
 'John',
 'Mary',
 'Sandra',
 'apple',
 'back',
 'bathroom',
 'bedroom',
 'discarded',
 'down',
 'dropped',
 'football',
 'garden',
 'got',
 'grabbed',
 'hallway',
 'in',
 'journeyed',
 'kitchen',
 'left',
 'milk',
 'moved',
 'no',
 'office',
 'picked',
 'put',
 'the',
 'there',
 'to',
 'took',
 'travelled',
 'up',
 'went',
 'yes']

In [ ]:
vocab_len = len(vocab) + 1

In [ ]:
vocab_len

38

In [ ]:
# longest story

all_story_lens = [len(data[0]) for data in all_data]

In [ ]:
max_story_len = max(all_story_lens)

In [ ]:
max_question_len = max(len(data[1]) for data in all_data)

In [ ]:
max_question_len

6

In [ ]:
from keras.preprocessing.sequence import pad_sequences
from keras.preprocessing.text import Tokenizer

In [ ]:
tokenizer =  Tokenizer(filters=[])
tokenizer.fit_on_texts(vocab)

In [ ]:
tokenizer.word_index

{'.': 37,
 '?': 28,
 'apple': 24,
 'back': 3,
 'bathroom': 33,
 'bedroom': 36,
 'daniel': 18,
 'discarded': 19,
 'down': 2,
 'dropped': 31,
 'football': 27,
 'garden': 20,
 'got': 26,
 'grabbed': 29,
 'hallway': 35,
 'in': 12,
 'is': 11,
 'john': 17,
 'journeyed': 5,
 'kitchen': 4,
 'left': 22,
 'mary': 34,
 'milk': 23,
 'moved': 25,
 'no': 14,
 'office': 10,
 'picked': 9,
 'put': 7,
 'sandra': 8,
 'the': 32,
 'there': 30,
 'to': 16,
 'took': 1,
 'travelled': 6,
 'up': 13,
 'went': 15,
 'yes': 21}

In [ ]:
train_story_text = []

In [ ]:
train_question_text = []

In [ ]:
train_answers = []

In [ ]:
for story, question, answer in train_data:
  train_story_text.append(story)
  train_question_text.append(question)
  train_answers.append(answer)

In [ ]:
#train_story_text

In [ ]:
train_story_seq = tokenizer.texts_to_sequences(train_story_text)

In [ ]:
len(train_story_seq)

10000

In [ ]:
type(train_story_seq)

list

In [ ]:
def vectorize_stories(data,
                     word_index = tokenizer.word_index,
                     max_story_len = max_story_len,
                     max_question_len = max_question_len):
  
  #stories
  X = []

  # questions
  Xq = []

  # answer
  Y = []

  for story, query, answer in data:

    x = [word_index[word.lower()] for word in story]
    xq = [word_index[word.lower()] for word in question]
    y = np.zeros(len(word_index)+1)

    y[word_index[answer]] = 1

    X.append(x)
    Xq.append(xq)
    Y.append(y)

  return (pad_sequences(X,maxlen=max_story_len),pad_sequences(Xq, maxlen=max_question_len),np.array(Y))



In [ ]:
inputs_train , queries_train, answers_train = vectorize_stories(train_data)

In [ ]:
inputs_test , queries_test, answers_test = vectorize_stories(test_data)

In [ ]:
inputs_test

array([[ 0,  0,  0, ..., 32, 36, 37],
       [ 0,  0,  0, ..., 32, 20, 37],
       [ 0,  0,  0, ..., 32, 20, 37],
       ...,
       [ 0,  0,  0, ..., 32, 24, 37],
       [ 0,  0,  0, ..., 32, 20, 37],
       [ 0,  0,  0, ..., 24, 30, 37]], dtype=int32)

In [ ]:
answers_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
tokenizer.word_index['yes']

21

In [ ]:
tokenizer.word_index['no']

14

In [ ]:
sum(answers_test)

array([  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0., 503.,   0.,   0.,   0.,   0.,   0.,   0., 497.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.])

In [ ]:
from keras.models import Sequential, Model

In [ ]:
from keras.layers.embeddings import Embedding

In [ ]:
from keras.layers import Input, Activation, Dense, Permute, Dropout, Add, Dot, Concatenate, LSTM

In [ ]:
input_sequence = Input((max_story_len,))
question = Input((max_question_len,))
vocab_size = len(vocab) + 1

In [ ]:
# input encoder M

input_encoder_m = Sequential()
input_encoder_m.add(Embedding(input_dim=vocab_size,output_dim=64))
input_encoder_m.add(Dropout(0.3))

# output
# (samples, story_maxlen, embedding_dim)

In [ ]:
# input encoder c

input_encoder_c = Sequential()
input_encoder_c.add(Embedding(input_dim=vocab_size,output_dim=max_question_len))
input_encoder_c.add(Dropout(0.3))

# output
# (samples, story_maxlen, embedding_dim)

In [ ]:
question_encoder = Sequential()
question_encoder.add(Embedding(input_dim=vocab_size,
                               output_dim=64,
                               input_length=max_question_len))
question_encoder.add(Dropout(0.3))

In [ ]:
# encoded --> encoder(input)

input_encoded_m = input_encoder_m(input_sequence)

In [ ]:
input_encoded_c = input_encoder_c(input_sequence)

In [ ]:
question_encoded = question_encoder(question)